Fix: Checks for APK path exist before uploading debug APK

diff --git a/.github/workflows/android-ci.yml b/.github/workflows/android-ci.yml
--- a/.github/workflows/android-ci.yml
+++ b/.github/workflows/android-ci.yml
@@ -38,8 +38,17 @@ jobs:
       - name: List APK folder contents
         run: ls -R app/build/outputs/apk/debug/
 
+      - name: Debug APK existence
+        run: |
+          echo "Checking for APK..."
+          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
+            echo "APK found!"
+          else
+            echo "APK NOT found!"
+            exit 1
+          fi
+
       - name: Upload Debug APK
-        if: success()
         uses: actions/upload-artifact@v3
         with:
           name: debug-apk
